### ISSUE TITLE
Is this triggerbot or what 

### ISSUE THREAD

**Issue by TherFdurdv32** [Leksa667IsBack/Valorant-Trigger-Bot-Undetected-Cheat-for-All-Windows-Versions#1]
Chances of ban and how is this different from others.

**Comment by Leksa667IsBack** [comment]
Yeah it's trigger bot work with colors normally the chances of getting banned are lower because the cheat does not read the memory afterwards there are lots of parameters to take into account and there is always a risk, however if you are smart you can improve it and make it undetectable !
